"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GUI.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'GUI.icns',
    'plist': {'CFBundleShortVersionString':'1.0.0',}
}

setup(
    app=APP,
    name='GUI',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)